### ISSUE TITLE
Se listan nedan.

### ISSUE THREAD

**Issue by jensnti** [marcusbillman/wsp1-gamebook#1]
Planering, skriv i repots README.md vid behov. Gör en docs/ folder med dokumentation (text, skisser osv.).

*** Gör en skiss över gränssnittet. Använd Figma om du önskar.**

Testa

*** Validera HTML och CSS.**

**Dokumentation**
* Reflektera över arbetsprocessen.
* Vad gick bra, skriv om planering/design/backend/frontend/test.
* Vad gick mindre bra?
* Vad behöver du lära dig mer om, vad vill du lära dig mer om.

**Comment by marcusbillman** [comment]
Jag har dokumentationen i min [GitHub Wiki](https://github.com/marcusbillman/wsp1-gamebook/wiki), men jag har nu även lagt till Markdown-filerna i en `docs`-mapp i repositoryt samt förtydligat i readme. Från Markdown-filerna kan man komma åt mitt [Google Dokument](https://docs.google.com/document/d/1u5z6cIKHUDQbtocbRcvWk8-JjXpTUlFn6maNVr8XJ1E/edit?usp=sharing) och mitt [flödesschema](https://drive.google.com/file/d/186KD1aWBwMecRII_4fiTelJVtgNRTVg9/view?usp=sharing).

Jag gjorde en Figma-skiss innan jag stilade min sida. Det står lite om den i min dokumentation.

Jag validerade nu också min Pug-märktext med hjälp av en [Pug-till-HTML-konverterare](https://pughtml.com/) och [W3C:s markup-valideringstjänst](https://validator.w3.org/) och den gick igenom. Även min kompilerade CSS validerar korrekt enligt [W3C Jigsaw](http://jigsaw.w3.org/css-validator/).

**Comment by jensnti** [comment]
Toppen Marcus, då var det jag som missade det.
Ska kolla!
